// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMySystem {
  function addEntry(string memory name, string memory color) external returns (bytes32);
}
